[package]
name = "rust-cube"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.21.0"
game-loop = "0.8.0"
image = "0.23.14"